# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spring',
            new_name='Sprint',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='spring',
            new_name='sprint',
        ),
    ]
